# Generated by Django 6.0 on 2026-03-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
