# Generated by Django 6.0 on 2026-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0002_userprofile_password_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
