# Generated by Django 6.0 on 2026-03-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0003_book_avg_rating_book_num_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
